
#############
### ALIGN ###
#############
taxonomy:
  nodes: "data/taxdump/nodes.dmp"
  names: "data/taxdump/names.dmp"

ref:
  test:
    n_shards: 2
    path: "data/test.{n_shard}-of-2"
    map:
      tool: dragen
      params: "--Mapper.edit-mode=0"
    acc2taxid: "data/test.acc2taxid.gz"

filter:
  saturated_reads:
    activate: true
    n_alns: 10

unicorn:
  refstats:
    params: "--minrefl 0 --minreads 1"
  taxstats:
    params: "--rank genus"

metadmg:
  damage:
    params: "--print_length 15"

  lca:
    params: "--fix_ncbi 0 --how_many 15 --sim_score_low 0.95 --weight_type 0 --lca_rank genus"

  dfit:
    params: "--nopt 5 --showfits 2 --seed 12345"

report:
  multiqc: "--verbose"
